// Regenerates the frontend's view of the core's event payloads.
//
// ts-rs writes one ES-module .ts file per Rust struct. The frontend is not made
// of modules - every file is a plain script sharing one global scope - so those
// per-type modules are merged here into a single ambient declaration file:
// exports dropped, cross-type imports dropped (everything lands in one scope),
// doc comments kept.
//
//   npm run types:sync
//
// The merged file is committed, so a clean checkout type-checks without needing
// a Rust toolchain. The raw per-type output is not (see .gitignore).

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const RAW_DIR = path.join(ROOT, 'types', 'generated');
const OUT_FILE = path.join(ROOT, 'types', 'bee-ipc.d.ts');

// ts-rs exports as a side effect of its generated tests.
console.log('[types] running cargo test to export bindings...');
execFileSync('cargo', ['test', '--manifest-path', 'src-tauri/Cargo.toml', 'export_bindings'], {
  cwd: ROOT,
  stdio: 'inherit',
});

if (!fs.existsSync(RAW_DIR)) {
  console.error(`[types] no bindings at ${RAW_DIR} - is #[ts(export)] still on the structs?`);
  process.exit(1);
}

const files = fs.readdirSync(RAW_DIR).filter((f) => f.endsWith('.ts')).sort();
if (!files.length) {
  console.error('[types] bindings directory is empty - nothing to merge.');
  process.exit(1);
}

const blocks = files.map((file) => {
  const body = fs
    .readFileSync(path.join(RAW_DIR, file), 'utf8')
    // ts-rs's provenance banner: said once at the top of the merged file instead.
    .replace(/^\/\/ This file was generated by .*$/gm, '')
    // Cross-type imports are meaningless once everything shares one scope.
    .replace(/^import type .*$/gm, '')
    // `export type X` -> `type X`: an ambient global, not a module export.
    .replace(/^export /gm, '')
    .trim();
  return body;
});

const header = [
  '// GENERATED FILE - DO NOT EDIT.',
  '//',
  '// Produced from the Rust payload structs in src-tauri/src/bridge/events.rs by',
  '// `npm run types:sync`. Edit the Rust structs, not this file: they are what the',
  '// core actually serialises, which is the whole reason these types can be',
  '// trusted. Declared globally because the frontend files are scripts, not',
  '// modules - no import needed to use them.',
  '',
].join('\n');

fs.writeFileSync(OUT_FILE, `${header}\n${blocks.join('\n\n')}\n`);
console.log(`[types] merged ${files.length} type(s) into ${path.relative(ROOT, OUT_FILE)}`);
